steps:
    # Build the container image
    - name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "gcr.io/training-402210/github.com/realdavidalad/hello-world-js-for-docker-and-gcp-cloudrun:$COMMIT_SHA", "."]
    # Push the container image to Container Registry
    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/training-402210/github.com/realdavidalad/hello-world-js-for-docker-and-gcp-cloudrun:$COMMIT_SHA"]
    # Deploy container image to Cloud Run
    - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
      entrypoint: gcloud
      args:
          - "run"
          - "deploy"
          - "hello-world"
          - "--image"
          - "gcr.io/training-402210/github.com/realdavidalad/hello-world-js-for-docker-and-gcp-cloudrun:$COMMIT_SHA"
          - "--region"
          - "us-central1"
images:
    - "gcr.io/training-402210/github.com/realdavidalad/hello-world-js-for-docker-and-gcp-cloudrun:$COMMIT_SHA"