steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-world', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/hello-world']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'hello-world'
      - '--image'
      - 'gcr.io/$PROJECT_ID/hello-world'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1' # Change to your desired region
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'services', 'hello-world']

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: 'us-central1' # Change to your desired region
